"""Corrigindo erro UTC - Ãºltimo

Revision ID: 1af236e8559e
Revises: 74bfb9ecee09
Create Date: 2025-02-04 22:17:42.843014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1af236e8559e'
down_revision = '74bfb9ecee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###
