"""Corrigindo erro UTC - SET TIMEZONE

Revision ID: 1c397c71413f
Revises: 07efc15605d6
Create Date: 2025-02-04 22:13:00.091341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c397c71413f'
down_revision = '07efc15605d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###
